const MoviesTypes = {
  GET_MOVIES: "GET_MOVIES",
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_MOVIES_FAILURE: "GET_MOVIES_FAILURE",
  GET_ALL_GENRES: "GET_ALL_GENRES",
  GET_ALL_GENRES_SUCCESS: "GET_ALL_GENRES_SUCCESS",
  GET_ALL_GENRES_FAILURE: "GET_ALL_GENRES_FAILURE",
  ADD_MOVIE: "ADD_MOVIE"
};

export default MoviesTypes;
